#include "ytmselftest.h"

#include "appdatabase.h"
#include "cookieimport.h"
#include "innertube.h"
#include "library.h"
#include "secretstore.h"
#include "ytmsession.h"

#include <QDateTime>
#include <QDir>
#include <QElapsedTimer>
#include <QEventLoop>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QHostAddress>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkCookie>
#include <QRegularExpression>
#include <QSet>
#include <QSqlQuery>
#include <QTcpServer>
#include <QTcpSocket>
#include <QTimer>
#include <QUrl>

#include <functional>
#include <memory>
#include <utility>

namespace {

// One line per check, and a count at the end, as in connectionselftest.cpp.
// Descriptions stay ASCII and never hold a cookie value.
class Checks
{
public:
    explicit Checks(const char *prefix) : m_prefix(prefix) {}

    bool check(bool ok, const QString &what, const QString &detail = QString())
    {
        ++m_count;
        if (!ok)
            ++m_failed;
        const QString line = ok || detail.isEmpty() ? what : what + QStringLiteral("  -- ") + detail;
        qWarning("%s: %s  %s", m_prefix, ok ? "ok  " : "FAIL", qPrintable(line));
        return ok;
    }

    void note(const QString &text) { qWarning("%s: %s", m_prefix, qPrintable(text)); }

    int finish()
    {
        qWarning("%s: %d checks, %d failed", m_prefix, m_count, m_failed);
        return m_failed;
    }

private:
    const char *m_prefix;
    int m_count = 0;
    int m_failed = 0;
};

using Cookie = CookieImport::Cookie;
using Result = CookieImport::Result;
using Format = CookieImport::Format;

// — the fixtures: invented, every value marked TEST so a leak is easy to find —

// A cookies.txt file as a browser extension writes it for a private window
// signed in to YouTube Music, with what else such a file holds: google.com's
// cookies of the same names, a cookie for www.youtube.com alone, one for
// another path, one expired, a duplicate on a more specific domain, a line of
// six fields, and a line that is not a cookie at all.
const char *const kNetscapeLines[] = {
    "# Netscape HTTP Cookie File",
    "# https://curl.se/docs/http-cookies.html",
    "# This file was generated by a test. Edit at your own risk.",
    "",
    ".youtube.com\tTRUE\t/\tTRUE\t1830000000\tPREF\tTESTVAL-pref-1",
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1830000000\tLOGIN_INFO\tTESTVAL-login-info-2",
    ".youtube.com\tTRUE\t/\tFALSE\t1830000000\tAPISID\tTESTVAL-apisid-3",
    ".youtube.com\tTRUE\t/\tTRUE\t1830000000\tSAPISID\tTESTSAPISID123",
    ".youtube.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-1PAPISID\tTESTSECURE1PAPISID456",
    ".youtube.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-3PAPISID\tTESTSECURE3PAPISID789",
    "#HttpOnly_.youtube.com\tTRUE\t/\tFALSE\t1830000000\tHSID\tTESTVAL-hsid-4",
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1830000000\tSSID\tTESTVAL-ssid-5",
    ".youtube.com\tTRUE\t/\tFALSE\t1830000000\tSID\tTESTVAL-sid-youtube-6",
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-1PSID\tTESTVAL-1psid-7",
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-3PSID\tTESTVAL-3psid-8",
    ".youtube.com\tTRUE\t/\tFALSE\t1830000000\tSIDCC\tTESTVAL-sidcc-9",
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\tYSC\tTESTVAL-ysc-10",
    "music.youtube.com\tFALSE\t/\tTRUE\t1830000000\tSIDCC\tTESTVAL-sidcc-music-11",
    ".youtube.com\tTRUE\t/\tTRUE\t1830000000\tEMPTYVAL",
    "www.youtube.com\tFALSE\t/\tTRUE\t1830000000\tWWWONLY\tTESTVAL-www-12",
    ".youtube.com\tTRUE\t/watch\tTRUE\t1830000000\tWATCHPATH\tTESTVAL-watch-13",
    ".google.com\tTRUE\t/\tTRUE\t1830000000\tSID\tTESTVAL-sid-google-14",
    "#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tLOGIN_INFO\tTESTVAL-google-login-15",
    ".youtube.com\tTRUE\t/\tTRUE\t1600000000\tOLDCOOKIE\tTESTVAL-expired-16",
    "this line is not a cookie at all",
};

// What of it is kept, in order, and what SIDCC and SID must hold.
const char *const kKeptNames[] = {
    "PREF", "LOGIN_INFO", "APISID", "SAPISID", "__Secure-1PAPISID", "__Secure-3PAPISID", "HSID", "SSID",
    "SID", "__Secure-1PSID", "__Secure-3PSID", "SIDCC", "YSC", "EMPTYVAL",
};

// Every value above and below, for the checks that none reaches a message or
// the log.
const char *const kValues[] = {
    "TESTVAL-pref-1", "TESTVAL-login-info-2", "TESTVAL-apisid-3", "TESTSAPISID123", "TESTSECURE1PAPISID456",
    "TESTSECURE3PAPISID789", "TESTVAL-hsid-4", "TESTVAL-ssid-5", "TESTVAL-sid-youtube-6", "TESTVAL-1psid-7",
    "TESTVAL-3psid-8", "TESTVAL-sidcc-9", "TESTVAL-ysc-10", "TESTVAL-sidcc-music-11", "TESTVAL-www-12",
    "TESTVAL-watch-13", "TESTVAL-sid-google-14", "TESTVAL-google-login-15", "TESTVAL-expired-16",
    "TESTVAL-sid-dup", "TESTVAL-login%&x", "TESTROTATED-sidcc", "TESTROTATED-new",
    // The known answers' digests: an Authorization header is as good as the cookie.
    "f4b52ff9a48e3c8447cf5c2dc974c2c9b0a1e946", "b872625234e084a7ffe7f8544bc00cff94e62daa",
    "31dcc68e15800ea041c83c1cbb49e65ba892eddf",
};

QByteArray netscapeFixture(const std::function<bool(const QByteArray &)> &keep = {})
{
    QByteArray text;
    for (const char *line : kNetscapeLines) {
        if (!keep || keep(QByteArray(line)))
            text += QByteArray(line) + '\n';
    }
    return text;
}

// The same session as a Cookie header, with a second SID (the first stays).
const QByteArray kHeader =
    "Cookie: PREF=TESTVAL-pref-1; LOGIN_INFO=TESTVAL-login-info-2; SAPISID=TESTSAPISID123; "
    "__Secure-1PAPISID=TESTSECURE1PAPISID456; __Secure-3PAPISID=TESTSECURE3PAPISID789; "
    "SID=TESTVAL-sid-youtube-6; SID=TESTVAL-sid-dup; YSC=TESTVAL-ysc-10";

Cookie find(const QList<Cookie> &cookies, const QByteArray &name)
{
    for (const Cookie &cookie : cookies) {
        if (cookie.name == name)
            return cookie;
    }
    return Cookie();
}

bool has(const QList<Cookie> &cookies, const QByteArray &name)
{
    for (const Cookie &cookie : cookies) {
        if (cookie.name == name)
            return true;
    }
    return false;
}

bool same(const Cookie &a, const Cookie &b)
{
    return a.name == b.name && a.value == b.value && a.domain == b.domain && a.hostOnly == b.hostOnly
           && a.path == b.path && a.expires == b.expires && a.secure == b.secure && a.httpOnly == b.httpOnly;
}

bool sameJar(const QList<Cookie> &a, const QList<Cookie> &b)
{
    if (a.size() != b.size())
        return false;
    for (int i = 0; i < a.size(); ++i) {
        if (!same(a.at(i), b.at(i)))
            return false;
    }
    return true;
}

QString counts(const Result &r)
{
    return QStringLiteral("read %1, kept %2, other sites %3, elsewhere %4, expired %5, duplicates %6, "
                          "unreadable %7, spaced %8")
        .arg(r.read).arg(r.cookies.size()).arg(r.otherSites).arg(r.elsewhere).arg(r.expired)
        .arg(r.duplicates).arg(r.unreadable).arg(r.spaced);
}

// Which fixture values a piece of text gives away; empty when none.
QStringList leaks(const QString &text)
{
    QStringList found;
    for (const char *value : kValues) {
        if (text.contains(QLatin1String(value)))
            found << QString::fromLatin1(value).left(8) + QStringLiteral("...");
    }
    return found;
}

// Runs the event loop until `done` holds or `timeoutMs` passes.
bool waitUntil(const std::function<bool()> &done, int timeoutMs)
{
    if (done())
        return true;
    QEventLoop loop;
    QTimer poll;
    poll.setInterval(10);
    QObject::connect(&poll, &QTimer::timeout, &loop, [&]() {
        if (done())
            loop.quit();
    });
    QTimer::singleShot(timeoutMs, &loop, &QEventLoop::quit);
    poll.start();
    loop.exec();
    return done();
}

void settle(int ms)
{
    QEventLoop loop;
    QTimer::singleShot(ms, &loop, &QEventLoop::quit);
    loop.exec();
}

}

int runCookieImportSelfTest()
{
    Checks t("cookies");
    constexpr qint64 kNow = 1790000000;   // 2026-09-21, fixed so expiry is the same on every run
    QStringList messages;                 // every error and summary, for the leak check at the end
    const auto keep = [&messages](const Result &r) {
        messages << r.error << r.summary();
        return r;
    };

    // — cookies.txt —
    const QByteArray netscape = netscapeFixture();
    const Result lf = keep(CookieImport::parse(netscape, kNow));
    t.check(lf.ok() && lf.format == Format::Netscape, QStringLiteral("a cookies.txt file (LF) is a signed-in session"),
            lf.error);
    t.check(lf.read == 20 && lf.cookies.size() == 14 && lf.otherSites == 2 && lf.elsewhere == 2 && lf.expired == 1
                && lf.duplicates == 1 && lf.unreadable == 1 && lf.spaced == 0,
            QStringLiteral("counts: 20 read, 14 kept, 2 other sites, 2 elsewhere on YouTube, 1 expired, 1 duplicate, "
                           "1 unreadable"), counts(lf));
    {
        QStringList expected;
        for (const char *name : kKeptNames)
            expected << QString::fromLatin1(name);
        t.check(CookieImport::names(lf.cookies) == expected, QStringLiteral("the names kept, in the order read"),
                CookieImport::names(lf.cookies).join(QLatin1Char(',')));
    }
    t.note(QStringLiteral("summary: ") + lf.summary());
    {
        const Cookie login = find(lf.cookies, "LOGIN_INFO");
        t.check(login.value == "TESTVAL-login-info-2" && login.httpOnly && login.secure && login.domain == QLatin1String("youtube.com")
                    && !login.hostOnly && login.expires == 1830000000,
                QStringLiteral("#HttpOnly_ lines are cookies: LOGIN_INFO kept, HttpOnly, .youtube.com"));
        t.check(!find(lf.cookies, "SAPISID").httpOnly && find(lf.cookies, "HSID").httpOnly
                    && !find(lf.cookies, "HSID").secure,
                QStringLiteral("HttpOnly and Secure are read per line"));
        const Cookie sidcc = find(lf.cookies, "SIDCC");
        t.check(sidcc.value == "TESTVAL-sidcc-music-11" && sidcc.domain == QLatin1String("music.youtube.com") && sidcc.hostOnly,
                QStringLiteral("SIDCC on .youtube.com and on music.youtube.com: the more specific copy wins"));
        t.check(find(lf.cookies, "SID").value == "TESTVAL-sid-youtube-6",
                QStringLiteral("SID on google.com is left out, and YouTube's own copy kept"));
        t.check(find(lf.cookies, "YSC").expires == 0, QStringLiteral("a session cookie (expiry 0) is kept"));
        t.check(has(lf.cookies, "EMPTYVAL") && find(lf.cookies, "EMPTYVAL").value.isEmpty(),
                QStringLiteral("a line of six fields is a cookie with an empty value"));
        t.check(!has(lf.cookies, "WWWONLY") && !has(lf.cookies, "WATCHPATH") && !has(lf.cookies, "OLDCOOKIE"),
                QStringLiteral("www.youtube.com's own, /watch's, and expired cookies are left out"));
    }

    // Line ends, and a byte-order mark.
    {
        QByteArray crlf = netscape;
        crlf.replace("\n", "\r\n");
        const Result r = keep(CookieImport::parse(crlf, kNow));
        t.check(r.ok() && sameJar(r.cookies, lf.cookies) && r.read == lf.read,
                QStringLiteral("the same file with CRLF line ends reads the same"), r.error);
        const Result bom = keep(CookieImport::parse(QByteArray("\xEF\xBB\xBF") + crlf, kNow));
        t.check(bom.ok() && sameJar(bom.cookies, lf.cookies),
                QStringLiteral("and with a UTF-8 byte-order mark in front"), bom.error);
    }

    // Expiries no whole number of seconds can hold: refused as unreadable,
    // never turned into some other time (converting them is undefined).
    {
        const QByteArray odd = netscape
                               + ".youtube.com\tTRUE\t/\tTRUE\t1e300\tHUGEEXPIRY\tTESTVAL-huge\n"
                               + ".youtube.com\tTRUE\t/\tTRUE\tinf\tINFEXPIRY\tTESTVAL-inf\n"
                               + ".youtube.com\tTRUE\t/\tTRUE\tnan\tNANEXPIRY\tTESTVAL-nan\n"
                               + ".youtube.com\tTRUE\t/\tTRUE\t9300000000000000000\tOVERFLOW\tTESTVAL-overflow\n"
                               + ".youtube.com\tTRUE\t/\tTRUE\t253402300799\tYEAR9999\tTESTVAL-9999\n";
        const Result r = keep(CookieImport::parse(odd, kNow));
        t.check(r.ok() && r.unreadable == lf.unreadable + 4 && !has(r.cookies, "HUGEEXPIRY")
                    && !has(r.cookies, "INFEXPIRY") && !has(r.cookies, "NANEXPIRY") && !has(r.cookies, "OVERFLOW")
                    && find(r.cookies, "YEAR9999").expires == 253402300799LL,
                QStringLiteral("expiries of 1e300, inf, nan and past 2^63: unreadable; the end of 9999 is kept"),
                counts(r));
    }

    // Spaces where the tabs go.
    {
        QByteArray spaced = netscape;
        spaced.replace('\t', ' ');
        const Result r = keep(CookieImport::parse(spaced, kNow));
        t.check(!r.ok() && r.format == Format::Netscape && r.spaced == 20 && r.cookies.isEmpty()
                    && r.error.contains(QLatin1String("tabs")),
                QStringLiteral("spaces where the tabs go: refused, and it says so"), counts(r) + QStringLiteral("; ") + r.error);
        // One spaced line among good ones is skipped, and the rest still count.
        QByteArray oneSpaced = netscape;
        oneSpaced.replace(".youtube.com\tTRUE\t/\tTRUE\t1830000000\tPREF\tTESTVAL-pref-1",
                          ".youtube.com TRUE / TRUE 1830000000 PREF TESTVAL-pref-1");
        const Result mixed = keep(CookieImport::parse(oneSpaced, kNow));
        t.check(mixed.ok() && mixed.spaced == 1 && !has(mixed.cookies, "PREF") && mixed.cookies.size() == 13,
                QStringLiteral("one spaced line among good ones is skipped, the rest kept"), counts(mixed));
    }

    // What reading #HttpOnly_ as a comment would cost.
    {
        QByteArray commented = netscape;
        commented.replace("#HttpOnly_", "# HttpOnly_");
        const Result r = keep(CookieImport::parse(commented, kNow));
        t.check(!r.ok() && r.missing.contains(QStringLiteral("LOGIN_INFO")),
                QStringLiteral("(the same file with its HttpOnly lines commented out has no LOGIN_INFO: refused)"),
                r.error);
    }

    // Not a session.
    {
        const Result noLogin = keep(CookieImport::parse(
            netscapeFixture([](const QByteArray &line) { return !line.contains("LOGIN_INFO"); }), kNow));
        t.check(!noLogin.ok() && noLogin.cookies.isEmpty() && noLogin.error.contains(QLatin1String("LOGIN_INFO")),
                QStringLiteral("no LOGIN_INFO: refused, naming it"), noLogin.error);
        const Result noSapisid = keep(CookieImport::parse(
            netscapeFixture([](const QByteArray &line) { return !line.contains("APISID\t"); }), kNow));
        t.check(!noSapisid.ok() && noSapisid.error.contains(QLatin1String("SAPISID")),
                QStringLiteral("no SAPISID, __Secure-1PAPISID or __Secure-3PAPISID: refused, naming SAPISID"),
                noSapisid.error);
        const Result googleOnly = keep(CookieImport::parse(
            netscapeFixture([](const QByteArray &line) { return !line.contains("youtube.com"); }), kNow));
        t.check(!googleOnly.ok() && googleOnly.otherSites == 2 && googleOnly.error.contains(QLatin1String("None of these")),
                QStringLiteral("google.com's cookies only: refused"), googleOnly.error);
        const Result expired = keep(CookieImport::parse(netscape, 1840000000));
        t.check(!expired.ok() && expired.error.contains(QLatin1String("LOGIN_INFO"))
                    && expired.error.contains(QLatin1String("expired")),
                QStringLiteral("the same file read after it expired: refused, saying so"), expired.error);
        const Result nothing = keep(CookieImport::parse("# Netscape HTTP Cookie File\n\n", kNow));
        t.check(!nothing.ok() && nothing.error.contains(QLatin1String("no cookies")),
                QStringLiteral("a cookies.txt file with no cookies: refused"), nothing.error);
    }

    // — the Cookie header —
    {
        const Result r = keep(CookieImport::parse(kHeader, kNow));
        t.check(r.ok() && r.format == Format::Header && r.cookies.size() == 7 && r.duplicates == 1,
                QStringLiteral("a Cookie header: 7 cookies, 1 duplicate"), counts(r) + QStringLiteral("; ") + r.error);
        const Cookie sid = find(r.cookies, "SID");
        t.check(sid.value == "TESTVAL-sid-youtube-6" && sid.domain == QLatin1String("youtube.com") && !sid.hostOnly
                    && sid.secure && sid.path == QLatin1String("/"),
                QStringLiteral("a header's cookies count as .youtube.com, path /, secure; the first SID stays"));
        const Result lower = keep(CookieImport::parse(QByteArray(kHeader).replace("Cookie:", "cookie:"), kNow));
        t.check(lower.ok() && sameJar(lower.cookies, r.cookies), QStringLiteral("\"cookie:\" in lower case"));
        const Result bare = keep(CookieImport::parse(kHeader.mid(int(qstrlen("Cookie: "))), kNow));
        t.check(bare.ok() && sameJar(bare.cookies, r.cookies), QStringLiteral("the value alone, without its name"));
        const QByteArray block = ":authority: music.youtube.com\r\naccept: */*\r\n"
                                 + QByteArray(kHeader).replace("Cookie:", "cookie:")
                                 + "\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)\r\n";
        const Result headers = keep(CookieImport::parse(block, kNow));
        t.check(headers.ok() && sameJar(headers.cookies, r.cookies),
                QStringLiteral("a whole block of request headers: the cookie line is found"), headers.error);
        const Result noCookie = keep(CookieImport::parse(":authority: music.youtube.com\naccept: */*\n", kNow));
        t.check(!noCookie.ok() && noCookie.error.contains(QLatin1String("no Cookie header")),
                QStringLiteral("request headers with no cookie line: refused, saying so"), noCookie.error);
        const Result onlySecure3 = keep(CookieImport::parse(
            "LOGIN_INFO=TESTVAL-login-info-2; __Secure-3PAPISID=TESTSECURE3PAPISID789", kNow));
        t.check(onlySecure3.ok(), QStringLiteral("LOGIN_INFO and __Secure-3PAPISID without SAPISID is a session"),
                onlySecure3.error);
        const Result header = keep(CookieImport::parse("SAPISID=TESTSAPISID123; SID=TESTVAL-sid-youtube-6", kNow));
        t.check(!header.ok() && header.error.contains(QLatin1String("LOGIN_INFO")),
                QStringLiteral("a header without LOGIN_INFO: refused"), header.error);
        const Result words = keep(CookieImport::parse("hello there", kNow));
        t.check(!words.ok() && words.format == Format::Header, QStringLiteral("plain words: refused"), words.error);
    }

    // — cURL —
    {
        const QByteArray bash =
            "curl 'https://music.youtube.com/youtubei/v1/browse?prettyPrint=false' \\\n"
            "  -H 'accept: */*' \\\n"
            "  -H 'content-type: application/json' \\\n"
            "  -b 'PREF=TESTVAL-pref-1; LOGIN_INFO=TESTVAL-login-info-2; SAPISID=TESTSAPISID123; "
            "__Secure-3PAPISID=TESTSECURE3PAPISID789' \\\n"
            "  -H 'origin: https://music.youtube.com' \\\n"
            "  --data-raw '{\"context\":{\"client\":{\"clientName\":\"WEB_REMIX\"}},\"browseId\":\"FEmusic_home\"}'";
        const Result r = keep(CookieImport::parse(bash, kNow));
        t.check(r.ok() && r.format == Format::Curl && CookieImport::names(r.cookies).join(QLatin1Char(','))
                    == QLatin1String("PREF,LOGIN_INFO,SAPISID,__Secure-3PAPISID")
                    && find(r.cookies, "SAPISID").value == "TESTSAPISID123",
                QStringLiteral("cURL (bash), cookies in -b, lines continued with a backslash"),
                counts(r) + QStringLiteral("; ") + r.error);
        QByteArray crlf = bash;
        crlf.replace("\n", "\r\n");
        const Result rc = keep(CookieImport::parse(crlf, kNow));
        t.check(rc.ok() && sameJar(rc.cookies, r.cookies), QStringLiteral("the same with CRLF line ends"), rc.error);

        const QByteArray header = "curl 'https://music.youtube.com/youtubei/v1/browse' -X POST "
                                  "-H 'User-Agent: Mozilla/5.0' -H '" + kHeader + "' --data-raw '{}'";
        const Result rh = keep(CookieImport::parse(header, kNow));
        t.check(rh.ok() && rh.cookies.size() == 7, QStringLiteral("cURL with -H 'Cookie: ...' (Firefox's copy)"),
                counts(rh) + QStringLiteral("; ") + rh.error);

        // $'...': what Chrome writes when a header holds a quote or a '!'.
        const QByteArray ansi = "curl 'https://music.youtube.com/' -H $'cookie: PREF=it\\'s; "
                                "LOGIN_INFO=TESTVAL\\u0021x; SAPISID=TESTSAPISID123'";
        const Result ra = keep(CookieImport::parse(ansi, kNow));
        t.check(ra.ok() && find(ra.cookies, "PREF").value == "it's" && find(ra.cookies, "LOGIN_INFO").value == "TESTVAL!x",
                QStringLiteral("cURL with $'...' quoting: \\' and \\u0021 decoded"), ra.error);

        // cmd.exe: Chrome's "Copy as cURL (cmd)".
        const QByteArray cmd =
            "curl ^\"https://music.youtube.com/youtubei/v1/browse?prettyPrint=false^\" ^\r\n"
            "  -H ^\"accept: */*^\" ^\r\n"
            "  -b ^\"PREF=TESTVAL-pref-1; LOGIN_INFO=TESTVAL-login^%^&x; SAPISID=TESTSAPISID123^\" ^\r\n"
            "  --data-raw ^\"^{^\\^\"context^\\^\":1^}^\"";
        const Result rw = keep(CookieImport::parse(cmd, kNow));
        t.check(rw.ok() && find(rw.cookies, "LOGIN_INFO").value == "TESTVAL-login%&x" && rw.cookies.size() == 3,
                QStringLiteral("cURL (cmd): carets and ^\" undone"), counts(rw) + QStringLiteral("; ") + rw.error);
        const QStringList words = CookieImport::commandWords(QString::fromUtf8(cmd), true);
        t.check(words.size() == 8 && words.last() == QLatin1String("{\"context\":1}"),
                QStringLiteral("cmd: the escaped JSON body decodes to its quotes"), words.join(QLatin1Char('|')));

        const Result file = keep(CookieImport::parse("curl 'https://music.youtube.com/' -b cookies.txt", kNow));
        t.check(!file.ok() && file.error.contains(QLatin1String("file")),
                QStringLiteral("cURL that reads its cookies from a file: refused, saying so"), file.error);
        const Result none = keep(CookieImport::parse("curl 'https://music.youtube.com/' -H 'accept: */*'", kNow));
        t.check(!none.ok() && none.error.contains(QLatin1String("no cookies")),
                QStringLiteral("cURL with no cookies: refused"), none.error);
    }

    // — the shells' words —
    {
        const QStringList posix = CookieImport::commandWords(
            QStringLiteral("a 'b c' \"d \\\"e\\\"\" $'f\\ng' h\\ i \\\n j"), false);
        t.check(posix == QStringList{ QStringLiteral("a"), QStringLiteral("b c"), QStringLiteral("d \"e\""),
                                      QStringLiteral("f\ng"), QStringLiteral("h i"), QStringLiteral("j") },
                QStringLiteral("bash: '...', \"...\", $'...', backslash escapes and continuations"),
                posix.join(QLatin1Char('|')));
        const QStringList windows = CookieImport::commandWords(
            QStringLiteral("curl ^\"a b^\" ^\"c\\^\"d^\" ^\"e\\\\f^\""), true);
        t.check(windows == QStringList{ QStringLiteral("curl"), QStringLiteral("a b"), QStringLiteral("c\"d"),
                                        QStringLiteral("e\\\\f") },
                QStringLiteral("cmd: carets, then the C runtime's quotes and backslashes"),
                windows.join(QLatin1Char('|')));
    }

    // — other things people paste —
    {
        const Result json = keep(CookieImport::parse(
            "[{\"domain\":\".youtube.com\",\"name\":\"SAPISID\",\"value\":\"TESTSAPISID123\"}]", kNow));
        t.check(!json.ok() && json.error.contains(QLatin1String("JSON")), QStringLiteral("a JSON export: refused, naming the format"),
                json.error);
        const Result ps = keep(CookieImport::parse(
            "$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession\n"
            "$session.Cookies.Add((New-Object System.Net.Cookie(\"SAPISID\", \"TESTSAPISID123\", \"/\", \".youtube.com\")))\n"
            "Invoke-WebRequest -UseBasicParsing -Uri \"https://music.youtube.com/\"", kNow));
        t.check(!ps.ok() && ps.error.contains(QLatin1String("PowerShell")), QStringLiteral("a PowerShell copy: refused"), ps.error);
        const Result empty = keep(CookieImport::parse(" \r\n\t ", kNow));
        t.check(!empty.ok() && empty.error.contains(QLatin1String("empty")), QStringLiteral("nothing at all: refused"), empty.error);
        const Result binary = keep(CookieImport::parse(QByteArray("PK\x03\x04\0\0binary", 12), kNow));
        t.check(!binary.ok(), QStringLiteral("a binary file: refused"), binary.error);
    }

    // — the jar as stored —
    {
        const QByteArray json = CookieImport::toJson(lf.cookies);
        QList<Cookie> back;
        t.check(CookieImport::fromJson(json, &back) && sameJar(back, lf.cookies),
                QStringLiteral("the jar round-trips through its JSON (%1 bytes)").arg(json.size()));
        QList<Cookie> high = lf.cookies;
        high[0].value = QByteArray("\x01\x7f\x80\xff", 4);
        QList<Cookie> highBack;
        t.check(CookieImport::fromJson(CookieImport::toJson(high), &highBack) && sameJar(highBack, high),
                QStringLiteral("every byte of a value survives it"));
        QList<Cookie> refused = lf.cookies;
        t.check(!CookieImport::fromJson("{\"version\":2,\"cookies\":[]}", &refused) && refused.isEmpty()
                    && !CookieImport::fromJson("not json", &refused)
                    && !CookieImport::fromJson(QByteArray(json).replace("youtube.com", "example.org"), &refused),
                QStringLiteral("another version, not JSON, or another site's cookies: refused, and nothing returned"));
    }

    // — the header sent —
    {
        const QByteArray expected =
            "PREF=TESTVAL-pref-1; LOGIN_INFO=TESTVAL-login-info-2; APISID=TESTVAL-apisid-3; SAPISID=TESTSAPISID123; "
            "__Secure-1PAPISID=TESTSECURE1PAPISID456; __Secure-3PAPISID=TESTSECURE3PAPISID789; HSID=TESTVAL-hsid-4; "
            "SSID=TESTVAL-ssid-5; SID=TESTVAL-sid-youtube-6; __Secure-1PSID=TESTVAL-1psid-7; "
            "__Secure-3PSID=TESTVAL-3psid-8; SIDCC=TESTVAL-sidcc-music-11; YSC=TESTVAL-ysc-10; EMPTYVAL=";
        t.check(CookieImport::header(lf.cookies, kNow) == expected,
                QStringLiteral("the Cookie header for music.youtube.com, byte for byte (compared, not shown)"));
        t.check(CookieImport::header(lf.cookies, 1840000000) == "YSC=TESTVAL-ysc-10",
                QStringLiteral("cookies that have expired since are left out of it"));
    }

    // — SAPISIDHASH: known answers, each SHA-1 computed apart from this code
    // (.NET's SHA1 over "<ts> <sid> <origin>") —
    {
        const QByteArray origin = YtmSession::kOrigin;
        const QByteArray one = YtmSession::sidHash("SAPISIDHASH", kNow, "TESTSAPISID123", origin);
        t.check(one == "SAPISIDHASH 1790000000_f4b52ff9a48e3c8447cf5c2dc974c2c9b0a1e946",
                QStringLiteral("SAPISIDHASH known answer"));
        const QByteArray all = YtmSession::authorization(lf.cookies, kNow, origin);
        t.check(all == "SAPISIDHASH 1790000000_f4b52ff9a48e3c8447cf5c2dc974c2c9b0a1e946 "
                       "SAPISID1PHASH 1790000000_b872625234e084a7ffe7f8544bc00cff94e62daa "
                       "SAPISID3PHASH 1790000000_31dcc68e15800ea041c83c1cbb49e65ba892eddf",
                QStringLiteral("all three schemes, space-separated, in yt-dlp's order"));
        static const QRegularExpression shape(
            QStringLiteral("^SAPISIDHASH \\d+_[0-9a-f]{40} SAPISID1PHASH \\d+_[0-9a-f]{40} SAPISID3PHASH \\d+_[0-9a-f]{40}$"));
        t.check(shape.match(QString::fromLatin1(all)).hasMatch(), QStringLiteral("lower-case hex, 40 digits each"));
        const Result third = CookieImport::parse(
            "LOGIN_INFO=TESTVAL-login-info-2; __Secure-3PAPISID=TESTSECURE3PAPISID789", kNow);
        t.check(YtmSession::authorization(third.cookies, kNow, origin)
                    == "SAPISIDHASH 1790000000_31dcc68e15800ea041c83c1cbb49e65ba892eddf "
                       "SAPISID3PHASH 1790000000_31dcc68e15800ea041c83c1cbb49e65ba892eddf",
                QStringLiteral("without SAPISID, SAPISIDHASH is made from __Secure-3PAPISID"));
        t.check(YtmSession::sidHash("SAPISIDHASH", kNow, "TESTSAPISID123", "https://www.youtube.com")
                    == "SAPISIDHASH 1790000000_f48fb12f67f79b5855f0c7bd9d6ea6702c85032d",
                QStringLiteral("the origin is part of the hash (www.youtube.com's differs)"));
        t.check(YtmSession::authorization({}, kNow, origin).isEmpty(), QStringLiteral("no SAPISID of any kind: no header"));
    }

    // — no value in any message —
    {
        QStringList found;
        for (const QString &message : std::as_const(messages))
            found << leaks(message);
        t.check(found.isEmpty(), QStringLiteral("no cookie value in any of %1 errors and summaries").arg(messages.size()),
                found.join(QStringLiteral(", ")));
    }
    return t.finish();
}

// ---------------------------------------------------------------- the session

namespace {

// A stand-in for music.youtube.com on this computer: it keeps every request
// exactly as it arrived, and answers as `respond` says. One request a
// connection, closed after the answer.
class StandIn : public QObject
{
public:
    struct Request {
        QByteArray head;   // the request line and headers, byte for byte
        QByteArray body;
        QByteArray path;
        QList<QPair<QByteArray, QByteArray>> headers;   // names in lower case

        QByteArray header(const QByteArray &name) const
        {
            for (const auto &pair : headers) {
                if (pair.first == name)
                    return pair.second;
            }
            return QByteArray();
        }
        bool has(const QByteArray &name) const
        {
            for (const auto &pair : headers) {
                if (pair.first == name)
                    return true;
            }
            return false;
        }
        QJsonObject json() const { return QJsonDocument::fromJson(body).object(); }
        bool authed() const { return has("authorization"); }
    };
    struct Answer {
        int status = 200;
        QByteArray body = "{}";
        QList<QByteArray> extra;
        bool drop = false;   // close the connection without a word
        bool hold = false;   // keep it open and never answer
    };

    std::function<Answer(const Request &)> respond;
    QList<Request> requests;

    bool listen()
    {
        connect(&m_server, &QTcpServer::newConnection, this, &StandIn::accept);
        return m_server.listen(QHostAddress::LocalHost, 0);
    }
    QString base() const { return QStringLiteral("http://127.0.0.1:%1").arg(m_server.serverPort()); }

private:
    void accept()
    {
        while (QTcpSocket *socket = m_server.nextPendingConnection()) {
            auto buffer = std::make_shared<QByteArray>();
            connect(socket, &QTcpSocket::disconnected, socket, &QObject::deleteLater);
            connect(socket, &QTcpSocket::readyRead, this, [this, socket, buffer]() {
                *buffer += socket->readAll();
                handle(socket, *buffer);
            });
        }
    }

    void handle(QTcpSocket *socket, QByteArray &buffer)
    {
        const int end = int(buffer.indexOf("\r\n\r\n"));
        if (end < 0)
            return;
        Request request;
        request.head = buffer.left(end + 4);
        const QList<QByteArray> lines = buffer.left(end).split('\n');
        const QList<QByteArray> first = lines.value(0).trimmed().split(' ');
        request.path = first.value(1);
        for (int i = 1; i < lines.size(); ++i) {
            const QByteArray line = lines.at(i).trimmed();
            const int colon = int(line.indexOf(':'));
            if (colon > 0)
                request.headers.append({ line.left(colon).trimmed().toLower(), line.mid(colon + 1).trimmed() });
        }
        const int length = request.header("content-length").toInt();
        if (buffer.size() < end + 4 + length)
            return;
        request.body = buffer.mid(end + 4, length);
        buffer.clear();
        requests.append(request);

        const Answer answer = respond ? respond(request) : Answer();
        if (answer.drop) {
            socket->abort();
            return;
        }
        if (answer.hold)
            return;
        const QByteArray reason = answer.status == 200 ? "OK" : answer.status == 400 ? "Bad Request"
                                : answer.status == 401 ? "Unauthorized" : answer.status == 403 ? "Forbidden"
                                                                                                : "Error";
        QByteArray out = "HTTP/1.1 " + QByteArray::number(answer.status) + ' ' + reason + "\r\n"
                         "Content-Type: application/json; charset=UTF-8\r\n"
                         "Content-Length: " + QByteArray::number(answer.body.size()) + "\r\n"
                         "Connection: close\r\n";
        for (const QByteArray &line : answer.extra)
            out += line + "\r\n";
        out += "\r\n" + answer.body;
        socket->write(out);
        socket->disconnectFromHost();
    }

    QTcpServer m_server;
};

// Every message logged while the test runs, whatever its level, to show no
// cookie value is ever among them.
QStringList *g_captured = nullptr;
QtMessageHandler g_previousHandler = nullptr;

void captureMessage(QtMsgType type, const QMessageLogContext &context, const QString &message)
{
    if (g_captured)
        g_captured->append(message);
    if (g_previousHandler)
        g_previousHandler(type, context, message);
}

QByteArray trackingAnswer(const QByteArray &loggedIn)
{
    const QByteArray params = loggedIn.isEmpty()
        ? QByteArray(R"({"key":"e","value":"1"})")
        : R"({"key":"logged_in","value":")" + loggedIn + R"("},{"key":"e","value":"1"})";
    return R"({"responseContext":{"serviceTrackingParams":[{"service":"GFEEDBACK","params":[)" + params
           + R"(]}]},"contents":{}})";
}

const QByteArray kSignedOutMenu =
    R"({"actions":[{"openPopupAction":{"popup":{"multiPageMenuRenderer":{"sections":[]}}}}]})";

QByteArray menuAnswer(const QString &name)
{
    return R"({"actions":[{"openPopupAction":{"popup":{"multiPageMenuRenderer":{"header":{"activeAccountHeaderRenderer":)"
           R"({"accountName":{"runs":[{"text":")" + name.toUtf8() + R"("}]},"channelHandle":{"runs":[{"text":"@monolisttest"}]}}}}}}}]})";
}

struct Answered {
    bool done = false;
    QJsonObject root;
    QString error;
};

Answered browseNow(InnerTube &tube, const QString &browseId, InnerTube::Auth auth)
{
    auto result = std::make_shared<Answered>();
    tube.browse(browseId, [result](const QJsonObject &root, const QString &error) {
        result->done = true;
        result->root = root;
        result->error = error;
    }, auth);
    waitUntil([result]() { return result->done; }, 20000);
    return *result;
}

// The settings table holds no cookie value, whatever key it might be under.
QStringList settingsLeaks()
{
    QStringList found;
    QSqlQuery q(AppDatabase::connection());
    q.exec(QStringLiteral("SELECT key, value FROM settings"));
    while (q.next()) {
        if (!leaks(q.value(1).toString()).isEmpty())
            found << q.value(0).toString();
    }
    return found;
}

// Everything but the request line: what varies between two identical calls
// is only the path, when the browse ids differ.
QByteArray withoutRequestLine(const QByteArray &head)
{
    return head.mid(head.indexOf("\r\n"));
}

}

int runYtmSessionSelfTest(Library *library)
{
    Checks t("ytm");
    if (qEnvironmentVariableIsEmpty("MONOLIST_DATA_DIR")) {
        t.check(false, QStringLiteral("MONOLIST_DATA_DIR is set"),
                QStringLiteral("refusing to run: this test replaces the stored YouTube Music session"));
        return t.finish();
    }
    const QString secretName = QStringLiteral("ytmusic.cookies");
    const QString nameKey = QStringLiteral("ytmusic.account_name");
    const bool storeHere = SecretStore::available();
    t.note(storeHere ? QStringLiteral("secret store: ") + SecretStore::backendName()
                     : QStringLiteral("no secret store here (") + SecretStore::unavailableReason()
                           + QStringLiteral("): the session is kept in memory, and the restart is skipped"));

    QStringList captured;
    g_captured = &captured;
    g_previousHandler = qInstallMessageHandler(captureMessage);

    StandIn standIn;
    if (!t.check(standIn.listen(), QStringLiteral("a stand-in server on this computer"))) {
        qInstallMessageHandler(g_previousHandler);
        g_captured = nullptr;
        return t.finish();
    }
    InnerTube::setTestServer(standIn.base());
    t.note(QStringLiteral("every request goes to ") + standIn.base() + QStringLiteral(", none to YouTube"));
    const QByteArray origin = standIn.base().toUtf8();

    int regionDrops = 0;
    QString dropped;
    InnerTube::setRegion(QString());
    InnerTube::setRegionRejectedHandler([&regionDrops, &dropped](const QString &code) {
        ++regionDrops;
        dropped = code;
    });

    // How the stand-in answers, set as each step needs.
    int authedStatus = 200;
    QByteArray homeLoggedIn = "1";
    bool dropAll = false;
    bool refuseJapan = false;
    bool redirectAuthed = false;
    standIn.respond = [&](const StandIn::Request &request) {
        StandIn::Answer answer;
        if (dropAll) {
            answer.drop = true;
            return answer;
        }
        const bool authed = request.authed();
        if (authed && redirectAuthed) {
            answer.status = 302;
            answer.extra << "Location: " + standIn.base().toUtf8() + "/redirected-elsewhere";
            return answer;
        }
        const QJsonObject body = request.json();
        const QString gl = body.value(QStringLiteral("context")).toObject().value(QStringLiteral("client"))
                               .toObject().value(QStringLiteral("gl")).toString();
        if (authed && authedStatus != 200) {
            answer.status = authedStatus;
            answer.body = R"({"error":{"code":)" + QByteArray::number(authedStatus) + R"(,"status":"REFUSED"}})";
            return answer;
        }
        if (!authed && refuseJapan && gl == QLatin1String("JP")) {
            answer.status = 400;
            answer.body = R"({"error":{"code":400,"status":"INVALID_ARGUMENT"}})";
            return answer;
        }
        if (!authed)
            answer.extra << "Set-Cookie: ANONTEST=anon; Path=/";
        if (request.path.contains("account/account_menu")) {
            answer.body = authed ? menuAnswer(QStringLiteral("Monolist Test")) : kSignedOutMenu;
        } else {
            answer.body = trackingAnswer(authed ? homeLoggedIn : QByteArray("0"));
            if (authed && body.value(QStringLiteral("browseId")).toString() == QLatin1String("FEtest_rotate")) {
                answer.extra << "Set-Cookie: SIDCC=TESTROTATED-sidcc; Domain=.youtube.com; Path=/; Secure; HttpOnly"
                             << "Set-Cookie: ROTATETEST=TESTROTATED-new; Path=/";
            }
        }
        return answer;
    };

    // A clean slate.
    SecretStore::remove(secretName);
    library->setSetting(nameKey, QString());
    const QByteArray fixture = QByteArray(netscapeFixture()).replace("\n", "\r\n");
    const Result expected = CookieImport::parse(fixture);
    t.check(expected.ok(), QStringLiteral("the fixture is a session"), expected.error);
    const QByteArray expectedCookie = CookieImport::header(expected.cookies);

    // — 1. signed out, as before —
    InnerTube consumer;   // stands for Catalog, Lyrics and the rest
    const Answered first = browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::Anonymous);
    t.check(first.done && first.error.isEmpty(), QStringLiteral("an anonymous call is answered"), first.error);
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::Anonymous);
    const StandIn::Request baseline = standIn.requests.last();
    t.check(baseline.header("cookie") == "ANONTEST=anon",
            QStringLiteral("the anonymous jar works as before: its own cookie goes back"), QString::fromLatin1(baseline.header("cookie")));
    {
        // What the code sets, and what Qt adds by itself; nothing else.
        const QList<QByteArray> allowed = { "host", "content-type", "content-length", "user-agent", "origin", "referer",
                                            "cookie", "connection", "accept-encoding", "accept-language" };
        QStringList extra;
        for (const auto &pair : baseline.headers) {
            if (!allowed.contains(pair.first))
                extra << QString::fromLatin1(pair.first);
        }
        t.check(extra.isEmpty() && !baseline.authed() && !baseline.has("x-origin") && !baseline.has("x-goog-authuser"),
                QStringLiteral("an anonymous call carries nothing of an account"), extra.join(QStringLiteral(", ")));
        QStringList names;
        for (const auto &pair : baseline.headers)
            names << QString::fromLatin1(pair.first);
        t.note(QStringLiteral("anonymous headers: ") + names.join(QStringLiteral(", ")));
    }
    const auto sameAsBaseline = [&baseline](const StandIn::Request &request) {
        return request.head == baseline.head && request.body == baseline.body;
    };
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::IfSignedIn);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("IfSignedIn with no account hook: byte for byte the anonymous request"));

    auto session = std::make_unique<YtmSession>(library);
    YtmSession::Timing timing;
    timing.launchCheckMs = 100;
    timing.recheckMs = 300;
    timing.retryMinMs = 10 * 60 * 1000;   // never within the test
    timing.saveDelayMs = 300;
    session->setTiming(timing);
    QStringList outcomes;
    const auto follow = [&outcomes](YtmSession *s) {
        QObject::connect(s, &YtmSession::checked, s, [&outcomes](const QString &outcome) { outcomes << outcome; });
    };
    follow(session.get());
    session->start();
    t.check(session->state() == QLatin1String("signedOut"), QStringLiteral("nothing stored: signed out"), session->state());
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::IfSignedIn);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("IfSignedIn while signed out: byte for byte the anonymous request"));

    // — 2. import, and the check —
    const auto waitVerdict = [&outcomes](int before) {
        return waitUntil([&outcomes, before]() { return outcomes.size() > before; }, 15000);
    };
    int requestsBefore = int(standIn.requests.size());
    int outcomesBefore = int(outcomes.size());
    t.check(session->importText(QString::fromUtf8(fixture)) && session->state() == QLatin1String("checking"),
            QStringLiteral("a pasted cookies.txt imports, and is being checked"), session->importError());
    waitVerdict(outcomesBefore);
    t.check(session->state() == QLatin1String("active") && session->accountName() == QLatin1String("Monolist Test"),
            QStringLiteral("logged_in=1 and the account menu's name: active, as Monolist Test"),
            session->state() + QStringLiteral(" / ") + session->accountName());
    t.check(library->settingValue(nameKey) == QLatin1String("Monolist Test"),
            QStringLiteral("the name, and only the name, is in settings"));
    {
        int menu = 0;
        int home = 0;
        bool headersRight = true;
        QString why;
        static const QRegularExpression stamp(QStringLiteral("^SAPISIDHASH (\\d+)_"));
        for (int i = requestsBefore; i < standIn.requests.size(); ++i) {
            const StandIn::Request &request = standIn.requests.at(i);
            menu += request.path.contains("account/account_menu");
            home += request.json().value(QStringLiteral("browseId")).toString() == QLatin1String("FEmusic_home");
            const QRegularExpressionMatch match = stamp.match(QString::fromLatin1(request.header("authorization")));
            const QByteArray authorization = match.hasMatch()
                ? YtmSession::authorization(expected.cookies, match.captured(1).toLongLong(), origin) : QByteArray();
            if (request.header("cookie") != expectedCookie)
                why += QStringLiteral(" cookie");
            if (!match.hasMatch() || request.header("authorization") != authorization)
                why += QStringLiteral(" authorization");
            if (request.header("x-origin") != origin || request.header("x-goog-authuser") != "0")
                why += QStringLiteral(" x-origin/x-goog-authuser");
            headersRight = headersRight && why.isEmpty();
        }
        t.check(menu == 1 && home == 1, QStringLiteral("the check asks account_menu and FEmusic_home, once each"),
                QStringLiteral("%1 and %2").arg(menu).arg(home));
        t.check(headersRight, QStringLiteral("both carry exactly the jar's Cookie (not the anonymous jar's), the three "
                                             "SID hashes, X-Origin and X-Goog-AuthUser: 0"), why);
    }
    if (storeHere) {
        QByteArray stored;
        QList<Cookie> jar;
        const bool read = SecretStore::read(secretName, &stored) == SecretStore::Status::Ok;
        t.check(read && CookieImport::fromJson(stored, &jar) && sameJar(jar, expected.cookies),
                QStringLiteral("the jar is kept in the secret store (%1 bytes of JSON)").arg(stored.size()));
        const QString folder = SecretStore::folderPath();
        if (!folder.isEmpty()) {
            QFile file(QDir(folder).filePath(QStringLiteral("ytmusic.cookies.dpapi")));
            const QByteArray onDisk = file.open(QIODevice::ReadOnly) ? file.readAll() : QByteArray();
            t.check(!onDisk.isEmpty() && !onDisk.contains("TESTSAPISID123") && !onDisk.contains("LOGIN_INFO"),
                    QStringLiteral("the file on disk (%1 bytes) holds neither names nor values in the clear").arg(onDisk.size()));
        }
    }
    t.check(settingsLeaks().isEmpty(), QStringLiteral("no cookie value anywhere in the settings table"),
            settingsLeaks().join(QStringLiteral(", ")));

    // — 3. only the calls that ask carry it —
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::Anonymous);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("while signed in, an anonymous call is byte for byte what it was signed out"));
    const Answered rotate = browseNow(consumer, QStringLiteral("FEtest_rotate"), InnerTube::Auth::IfSignedIn);
    {
        const StandIn::Request &request = standIn.requests.last();
        t.check(rotate.error.isEmpty() && request.authed() && request.header("cookie") == expectedCookie
                    && withoutRequestLine(request.head) != withoutRequestLine(baseline.head),
                QStringLiteral("an IfSignedIn call carries the account, and none of the anonymous jar"), rotate.error);
    }
    t.check(find(session->jar(), "SIDCC").value == "TESTROTATED-sidcc" && find(session->jar(), "SIDCC").domain == QLatin1String("youtube.com")
                && has(session->jar(), "ROTATETEST") && find(session->jar(), "ROTATETEST").hostOnly
                && session->savePending(),
            QStringLiteral("Set-Cookie on its answer rotates the session's jar (SIDCC replaced, ROTATETEST added)"));
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::Anonymous);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("and none of it lands in the anonymous jar: the next anonymous call is unchanged"));
    waitUntil([&session]() { return !session->savePending(); }, 5000);
    if (storeHere) {
        QByteArray stored;
        QList<Cookie> jar;
        SecretStore::read(secretName, &stored);
        CookieImport::fromJson(stored, &jar);
        t.check(find(jar, "SIDCC").value == "TESTROTATED-sidcc" && has(jar, "ROTATETEST"),
                QStringLiteral("the rotated jar is saved after the delay"));
    }

    // — 4. a 400 on a call with the account never touches the country —
    InnerTube::setRegion(QStringLiteral("JP"));
    authedStatus = 400;
    requestsBefore = int(standIn.requests.size());
    const Answered refused400 = browseNow(consumer, QStringLiteral("FEtest_400"), InnerTube::Auth::IfSignedIn);
    authedStatus = 200;
    {
        const bool two = standIn.requests.size() == requestsBefore + 2;
        const bool firstAuthed = two && standIn.requests.at(requestsBefore).authed();
        const bool thenAnonymous = two && !standIn.requests.at(requestsBefore + 1).authed()
                                   && standIn.requests.at(requestsBefore + 1).header("cookie") == "ANONTEST=anon";
        t.check(refused400.error.isEmpty() && firstAuthed && thenAnonymous,
                QStringLiteral("a 400 with the account: asked again without it, and answered"),
                QStringLiteral("%1 requests; %2").arg(standIn.requests.size() - requestsBefore).arg(refused400.error));
        t.check(InnerTube::region() == QLatin1String("JP") && regionDrops == 0,
                QStringLiteral("the chosen country is kept, and Library::dropRegion is never called"),
                QStringLiteral("region %1, %2 drops").arg(InnerTube::region()).arg(regionDrops));
        t.check(session->state() == QLatin1String("active") && !session->jar().isEmpty(),
                QStringLiteral("a 400 is not a verdict on the session: still active"), session->state());
    }

    // — 4b. a redirect with the account is never followed: the redirected
    // request would be a copy carrying the cookies and the Authorization —
    redirectAuthed = true;
    requestsBefore = int(standIn.requests.size());
    const Answered redirected = browseNow(consumer, QStringLiteral("FEtest_redirect"), InnerTube::Auth::IfSignedIn);
    redirectAuthed = false;
    {
        bool followed = false;
        for (int i = requestsBefore; i < standIn.requests.size(); ++i)
            followed = followed || standIn.requests.at(i).path.contains("redirected-elsewhere");
        const bool two = standIn.requests.size() == requestsBefore + 2;
        const bool thenAnonymous = two && standIn.requests.at(requestsBefore).authed()
                                   && !standIn.requests.at(requestsBefore + 1).authed();
        t.check(redirected.error.isEmpty() && !followed && thenAnonymous,
                QStringLiteral("a 302 to a call with the account: not followed, and asked again without it"),
                QStringLiteral("%1 requests, followed %2; %3").arg(standIn.requests.size() - requestsBefore)
                    .arg(followed ? QStringLiteral("yes") : QStringLiteral("no"), redirected.error));
        t.check(session->state() == QLatin1String("active") && !session->jar().isEmpty(),
                QStringLiteral("a redirect is not a verdict on the session: still active"), session->state());
    }

    // — 5. a country refused for everyone is still dropped, as before —
    refuseJapan = true;
    const Answered refusedRegion = browseNow(consumer, QStringLiteral("FEtest_region"), InnerTube::Auth::Anonymous);
    refuseJapan = false;
    t.check(refusedRegion.error.isEmpty() && regionDrops == 1 && dropped == QLatin1String("JP")
                && InnerTube::region() == InnerTube::systemRegion(),
            QStringLiteral("an anonymous 400 from a refused country: dropped, told, and asked again (unchanged)"),
            QStringLiteral("%1 drops of %2; %3").arg(regionDrops).arg(dropped, refusedRegion.error));
    InnerTube::setRegion(QString());

    // — 6. 403: the session is over —
    const quint64 oldSession = session->session();
    authedStatus = 403;
    const Answered refused403 = browseNow(consumer, QStringLiteral("FEtest_403"), InnerTube::Auth::IfSignedIn);
    authedStatus = 200;
    t.check(refused403.error.isEmpty() && !standIn.requests.last().authed(),
            QStringLiteral("a 403 with the account: asked again without it, and answered"), refused403.error);
    t.check(session->state() == QLatin1String("rejected") && session->jar().isEmpty()
                && session->statusLine().contains(QLatin1String("ended")),
            QStringLiteral("and the session is refused: rejected, the cookies dropped"), session->state());
    if (storeHere) {
        QByteArray gone;
        t.check(SecretStore::read(secretName, &gone) == SecretStore::Status::NotFound,
                QStringLiteral("the stored copy is deleted"));
    }
    t.check(library->settingValue(nameKey) == QLatin1String("Monolist Test"),
            QStringLiteral("the name stays, to say whose session ended"));
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::IfSignedIn);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("IfSignedIn after the refusal: byte for byte the anonymous request"));
    {
        const QNetworkCookie late(QByteArrayLiteral("SIDCC"), QByteArrayLiteral("TESTROTATED-sidcc"));
        session->absorbCookies(oldSession, { late });
        session->reportRejected(oldSession, 401);
        t.check(session->jar().isEmpty() && session->state() == QLatin1String("rejected"),
                QStringLiteral("a late answer for the old session changes nothing"));
    }

    // — 7. logged_in=0 is believed the second time —
    homeLoggedIn = "0";
    outcomesBefore = int(outcomes.size());
    requestsBefore = int(standIn.requests.size());
    session->importText(QString::fromUtf8(kHeader));
    waitVerdict(outcomesBefore);
    t.check(outcomes.value(outcomesBefore) == QLatin1String("again") && session->state() == QLatin1String("checking"),
            QStringLiteral("a first logged_in=0: asked once more, still checking"), outcomes.value(outcomesBefore));
    waitVerdict(outcomesBefore + 1);
    {
        int homes = 0;
        for (int i = requestsBefore; i < standIn.requests.size(); ++i)
            homes += standIn.requests.at(i).json().value(QStringLiteral("browseId")).toString() == QLatin1String("FEmusic_home");
        t.check(outcomes.value(outcomesBefore + 1) == QLatin1String("rejected") && session->state() == QLatin1String("rejected")
                    && homes == 2,
                QStringLiteral("a second logged_in=0: rejected, after two checks"),
                QStringLiteral("%1, %2 checks").arg(outcomes.value(outcomesBefore + 1)).arg(homes));
    }
    homeLoggedIn = "1";

    // — 8. no answer: kept, not believed either way —
    dropAll = true;
    outcomesBefore = int(outcomes.size());
    session->importText(QString::fromUtf8(fixture));
    waitVerdict(outcomesBefore);
    dropAll = false;
    {
        QByteArray cookie;
        QByteArray authorization;
        const bool ifSignedIn = session->authHeaders(InnerTube::Auth::IfSignedIn, origin, &cookie, &authorization) != 0;
        const bool checking = session->authHeaders(InnerTube::Auth::Checking, origin, &cookie, &authorization) != 0;
        t.check(outcomes.value(outcomesBefore) == QLatin1String("unreachable") && session->state() == QLatin1String("unreachable")
                    && !session->jar().isEmpty() && !ifSignedIn && checking,
                QStringLiteral("no answer: unreachable, the session kept but not used; only a check may carry it"),
                session->state());
        QByteArray stored;
        if (storeHere)
            t.check(SecretStore::read(secretName, &stored) == SecretStore::Status::Ok, QStringLiteral("and still stored"));
    }
    outcomesBefore = int(outcomes.size());
    session->checkNow();
    waitVerdict(outcomesBefore);
    t.check(session->state() == QLatin1String("active"), QStringLiteral("asked again once it answers: active"), session->state());

    // — 9. a restart —
    if (storeHere) {
        const QList<Cookie> before = session->jar();
        session.reset();
        session = std::make_unique<YtmSession>(library);
        session->setTiming(timing);
        follow(session.get());
        outcomesBefore = int(outcomes.size());
        session->start();
        t.check(session->state() == QLatin1String("checking") && sameJar(session->jar(), before)
                    && session->accountName() == QLatin1String("Monolist Test"),
                QStringLiteral("a restart restores the session, and checks it before using it"), session->state());
        waitVerdict(outcomesBefore);
        t.check(session->state() == QLatin1String("active"), QStringLiteral("then active"), session->state());
    }

    // — 10. sign out —
    session->signOut();
    {
        QByteArray gone;
        t.check(session->state() == QLatin1String("signedOut") && session->jar().isEmpty()
                    && library->settingValue(nameKey).isEmpty()
                    && (!storeHere || SecretStore::read(secretName, &gone) == SecretStore::Status::NotFound),
                QStringLiteral("sign out: the stored copy deleted, the name forgotten"), session->state());
    }
    browseNow(consumer, QStringLiteral("FEtest_anon"), InnerTube::Auth::IfSignedIn);
    t.check(sameAsBaseline(standIn.requests.last()),
            QStringLiteral("IfSignedIn after sign-out: byte for byte the anonymous request"));

    // — 11. a file, and the offer to delete it —
    {
        const QString folder = QFileInfo(AppDatabase::databaseFilePath()).absolutePath();
        const QString deletePath = QDir(folder).filePath(QStringLiteral("cookies-selftest.txt"));
        const QString keepPath = QDir(folder).filePath(QStringLiteral("cookies-selftest-keep.txt"));
        for (const QString &path : { deletePath, keepPath }) {
            QFile file(path);
            if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate) || file.write(fixture) != fixture.size())
                t.note(QStringLiteral("could not write the fixture file ") + QFileInfo(path).fileName());
        }
        outcomesBefore = int(outcomes.size());
        t.check(session->importFile(QUrl::fromLocalFile(deletePath))
                    && session->importedFileName() == QLatin1String("cookies-selftest.txt"),
                QStringLiteral("a file imports, and Monolist offers to delete it"), session->importError());
        waitVerdict(outcomesBefore);
        t.check(QFileInfo::exists(deletePath), QStringLiteral("the file is left where it was until the user answers"));
        t.check(session->deleteImportedFile() && !QFileInfo::exists(deletePath) && session->importedFileName().isEmpty(),
                QStringLiteral("\"delete the file\": it is gone, and the offer with it"));

        const bool refused = session->importText(QStringLiteral("SAPISID=TESTSAPISID123; SID=TESTVAL-sid-youtube-6"));
        t.check(!refused && session->importError().contains(QLatin1String("LOGIN_INFO"))
                    && session->state() == QLatin1String("active") && session->importedFileName().isEmpty(),
                QStringLiteral("a refused import says why and leaves the session as it was"), session->importError());

        outcomesBefore = int(outcomes.size());
        session->importFile(QUrl::fromLocalFile(keepPath));
        waitVerdict(outcomesBefore);
        session->keepImportedFile();
        t.check(QFileInfo::exists(keepPath) && session->importedFileName().isEmpty() && session->importError().isEmpty(),
                QStringLiteral("\"keep it\": the file stays, and the offer goes"));
        // The test's own fixture, not a user's file.
        QFile::remove(keepPath);
        session->signOut();
    }

    // — 12. the log —
    {
        g_captured = nullptr;
        qInstallMessageHandler(g_previousHandler);
        QStringList found;
        bool namesLogged = false;
        for (const QString &line : std::as_const(captured)) {
            found << leaks(line);
            namesLogged = namesLogged || (line.startsWith(QLatin1String("ytmusic: imported")) && line.contains(QLatin1String("LOGIN_INFO")));
        }
        t.check(found.isEmpty(), QStringLiteral("none of %1 lines logged during the test holds a cookie value or a hash")
                                     .arg(captured.size()), found.join(QStringLiteral(", ")));
        t.check(namesLogged, QStringLiteral("while the names are logged, for diagnosis"));
    }

    session.reset();
    SecretStore::remove(secretName);
    library->setSetting(nameKey, QString());
    InnerTube::setRegionRejectedHandler({});
    InnerTube::setTestServer(QString());
    settle(50);
    return t.finish();
}

// ---------------------------------------------------------------- the visitor id

namespace {

struct Played {
    bool done = false;
    QString url;
    QString error;
};

std::shared_ptr<Played> playLater(InnerTube &tube, const QString &videoId)
{
    auto result = std::make_shared<Played>();
    tube.player(videoId, [result](const QString &url, int, const QString &error) {
        result->done = true;
        result->url = url;
        result->error = error;
    });
    return result;
}

Played playNow(InnerTube &tube, const QString &videoId)
{
    const auto result = playLater(tube, videoId);
    waitUntil([result]() { return result->done; }, 20000);
    return *result;
}

// sw.js_data as it is shaped: ")]}'" and nested arrays, the id at
// [0][2][0][0][13] and again at [0][2][6].
QByteArray swJsData(const QString &id)
{
    const QJsonValue value = id.isEmpty() ? QJsonValue() : QJsonValue(id);
    QJsonArray device;                 // [0][2][0][0]
    for (int i = 0; i < 13; ++i)
        device.append(QJsonValue());
    device.append(value);              // [13]
    QJsonArray devices;                // [0][2][0]
    devices.append(device);
    QJsonArray config;                 // [0][2]
    config.append(devices);
    config.append(QStringLiteral("TESTKEY"));
    for (int i = 2; i < 6; ++i)
        config.append(QJsonValue());
    config.append(value);              // [6]
    QJsonArray entry;                  // [0]
    entry.append(QStringLiteral("yt.sw.adr"));
    entry.append(QJsonValue());
    entry.append(config);
    QJsonArray root;
    root.append(entry);
    return ")]}'\n" + QJsonDocument(root).toJson(QJsonDocument::Compact);
}

QString visitorOf(const StandIn::Request &request)
{
    return request.json().value(QStringLiteral("context")).toObject().value(QStringLiteral("client"))
        .toObject().value(QStringLiteral("visitorData")).toString();
}

}

int runVisitorSelfTest()
{
    Checks t("visitor");
    QStringList captured;
    g_captured = &captured;
    g_previousHandler = qInstallMessageHandler(captureMessage);

    StandIn standIn;
    if (!t.check(standIn.listen(), QStringLiteral("a stand-in server on this computer"))) {
        qInstallMessageHandler(g_previousHandler);
        g_captured = nullptr;
        return t.finish();
    }
    InnerTube::setTestServer(standIn.base());
    t.note(QStringLiteral("every request goes to ") + standIn.base() + QStringLiteral(", none to YouTube"));

    // How the stand-in answers. Every id and cookie is invented, and each
    // fetch hands out a new one, so the checks can tell them apart.
    int minted = 0;
    bool swFails = false;
    bool swNoId = false;
    bool homeNoId = false;
    bool refuseAll = false;
    QSet<QString> refused;
    const auto nextId = [&minted](const char *kind) {
        return QStringLiteral("TESTVISITOR%1%2").arg(QLatin1String(kind)).arg(++minted, 4, 10, QLatin1Char('0'));
    };
    QStringList mintedIds;
    standIn.respond = [&](const StandIn::Request &request) {
        StandIn::Answer answer;
        if (request.path == "/sw.js_data") {
            if (swFails) {
                answer.status = 404;
                answer.body = "{}";
                return answer;
            }
            const QString id = swNoId ? QString() : nextId("sw");
            mintedIds << id;
            answer.body = swJsData(id);
            if (!id.isEmpty())
                answer.extra << "Set-Cookie: VISITOR_INFO1_LIVE=TESTCOOKIE" + QByteArray::number(minted) + "; Path=/";
            return answer;
        }
        if (request.path == "/") {
            const QString id = homeNoId ? QString() : nextId("home");
            mintedIds << id;
            answer.body = "<html><script>var ytcfg={\"INNERTUBE_CONTEXT\":{\"client\":{"
                          + (id.isEmpty() ? QByteArray() : "\"visitorData\":\"" + id.toUtf8() + "\",")
                          + "\"hl\":\"en\"}}};</script></html>";
            return answer;
        }
        if (request.path.contains("/player")) {
            // So the jar is never empty when a renewal is sent, which must
            // still go without it.
            answer.extra << "Set-Cookie: PLAYERTEST=TESTCOOKIEplayer; Path=/";
            const QString visitor = QString::fromLatin1(request.header("x-goog-visitor-id"));
            if (refuseAll || refused.contains(visitor)) {
                answer.body = R"({"playabilityStatus":{"status":"LOGIN_REQUIRED","reason":"Sign in to confirm you are not a bot"}})";
            } else {
                answer.body = R"({"playabilityStatus":{"status":"OK"},"streamingData":{"adaptiveFormats":[)"
                              R"({"itag":251,"url":"http://127.0.0.1/audio-test","mimeType":"audio/webm; codecs=\"opus\"","bitrate":130000}]}})";
            }
            return answer;
        }
        return answer;   // browse and the rest: {}
    };
    const auto countSince = [&standIn](int from, const QByteArray &path) {
        int n = 0;
        for (int i = from; i < standIn.requests.size(); ++i)
            n += path == "/player" ? standIn.requests.at(i).path.contains("/player") : standIn.requests.at(i).path == path;
        return n;
    };
    // The paths asked since `from`, in order: "sw", "home", "player", "browse".
    const auto orderSince = [&standIn](int from) {
        QStringList order;
        for (int i = from; i < standIn.requests.size(); ++i) {
            const QByteArray path = standIn.requests.at(i).path;
            order << (path == "/sw.js_data" ? QStringLiteral("sw") : path == "/" ? QStringLiteral("home")
                      : path.contains("/player") ? QStringLiteral("player") : QStringLiteral("browse"));
        }
        return order.join(QLatin1Char(' '));
    };
    const auto lastPlayer = [&standIn]() {
        for (qsizetype i = standIn.requests.size() - 1; i >= 0; --i) {
            if (standIn.requests.at(i).path.contains("/player"))
                return standIn.requests.at(i);
        }
        return StandIn::Request();
    };

    // The settings table, in memory. setVisitorStore starts the holder
    // afresh, which is what a new launch does.
    const QString idKey = QStringLiteral("youtube.visitor_data");
    const QString atKey = QStringLiteral("youtube.visitor_data_at");
    const QString modeKey = QStringLiteral("youtube.visitor");
    QHash<QString, QString> settings;
    // The first client alone: the orders below are its own, and the second
    // client, with the renewal before it, is --player-client-test's.
    settings.insert(QStringLiteral("youtube.player_client"), QStringLiteral("first"));
    const auto launch = [&settings]() {
        InnerTube::setVisitorStore({
            [&settings](const QString &key) { return settings.value(key); },
            [&settings](const QString &key, const QString &value) { settings.insert(key, value); } });
    };
    const auto storedAgo = [&settings, &idKey, &atKey](const QString &id, qint64 seconds) {
        settings.insert(idKey, id);
        settings.insert(atKey, QDateTime::currentDateTimeUtc().addSecs(-seconds).toString(Qt::ISODate));
    };
    const auto storedAt = [&settings, &atKey]() {
        return QDateTime::fromString(settings.value(atKey), Qt::ISODate);
    };

    // — 1. a first launch: one fetch however many ask, and it is stored —
    launch();
    {
        InnerTube resolver;
        InnerTube prefetch;
        const int from = int(standIn.requests.size());
        const auto a = playLater(resolver, QStringLiteral("vid-first-a"));
        const auto b = playLater(prefetch, QStringLiteral("vid-first-b"));
        waitUntil([a, b]() { return a->done && b->done; }, 20000);
        const QString id = mintedIds.value(mintedIds.size() - 1);
        bool named = true;
        for (int i = from; i < standIn.requests.size(); ++i) {
            const StandIn::Request &request = standIn.requests.at(i);
            if (request.path.contains("/player"))
                named = named && request.header("x-goog-visitor-id") == id.toUtf8() && visitorOf(request) == id;
        }
        t.check(!a->url.isEmpty() && !b->url.isEmpty(), QStringLiteral("two objects asking at once are both answered"),
                a->error + b->error);
        t.check(orderSince(from) == QLatin1String("sw player player"),
                QStringLiteral("one sw.js_data fetch for both, before either /player; no home page"), orderSince(from));
        t.check(named, QStringLiteral("both /player calls name that id, in the header and the context"));
        t.check(!standIn.requests.at(from).has("cookie"), QStringLiteral("the fetch goes as a first visit, with no cookie"));
        const QDateTime at = storedAt();
        t.check(settings.value(idKey) == id && at.isValid() && qAbs(at.secsTo(QDateTime::currentDateTimeUtc())) < 60,
                QStringLiteral("it is stored, with the time it was fetched"), settings.value(atKey));

        // — 2. one jar: the fetch's cookie reaches an object that never fetched —
        InnerTube catalog;
        browseNow(catalog, QStringLiteral("FEtest_jar"), InnerTube::Auth::Anonymous);
        const QByteArray cookie = standIn.requests.last().header("cookie");
        t.check(cookie.contains("VISITOR_INFO1_LIVE=TESTCOOKIE"),
                QStringLiteral("the cookie sw.js_data set goes on another object's browse (one shared jar)"),
                QString::number(cookie.size()) + QStringLiteral(" bytes of Cookie"));
    }

    // — 3. the next launch: the stored id, and no fetch at all —
    {
        const QString id = settings.value(idKey);
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-stored"));
        t.check(!played.url.isEmpty() && orderSince(from) == QLatin1String("player")
                    && lastPlayer().header("x-goog-visitor-id") == id.toUtf8(),
                QStringLiteral("a stored id: /player at once with it, nothing fetched"), orderSince(from));
        settle(50);
        t.check(countSince(from, "/sw.js_data") == 0 && settings.value(idKey) == id,
                QStringLiteral("and under a day old, it is not renewed after the play"));
    }

    // — 4. a stored id over a day old is renewed after the first play —
    {
        const QString old = settings.value(idKey);
        storedAgo(old, 2 * 24 * 3600);
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-old"));
        const bool usedOld = lastPlayer().header("x-goog-visitor-id") == old.toUtf8();
        waitUntil([&]() { return settings.value(idKey) != old; }, 5000);
        t.check(!played.url.isEmpty() && usedOld && orderSince(from) == QLatin1String("player sw")
                    && !settings.value(idKey).isEmpty() && settings.value(idKey) != old,
                QStringLiteral("two days old: played with at once, then renewed in the background"), orderSince(from));
        const StandIn::Request renewal = standIn.requests.value(from + 1);
        InnerTube catalog;
        browseNow(catalog, QStringLiteral("FEtest_renewed"), InnerTube::Auth::Anonymous);
        t.check(!renewal.has("cookie") && standIn.requests.last().header("cookie").contains("PLAYERTEST="),
                QStringLiteral("the renewal goes without the jar's cookies (which a browse still carries), "
                               "so it is a new id, not the old one re-dated"));
        const QString renewed = settings.value(idKey);
        playNow(resolver, QStringLiteral("vid-after-renewal"));
        t.check(lastPlayer().header("x-goog-visitor-id") == renewed.toUtf8(),
                QStringLiteral("and the next /player names the new one"));
    }

    // — 5. past 30 days it is never used —
    {
        const QString old = settings.value(idKey);
        storedAgo(old, 31 * 24 * 3600);
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-expired"));
        const QByteArray used = lastPlayer().header("x-goog-visitor-id");
        t.check(!played.url.isEmpty() && orderSince(from) == QLatin1String("sw player") && used != old.toUtf8()
                    && used == settings.value(idKey).toUtf8(),
                QStringLiteral("31 days old: dropped, a new one fetched first and stored"), orderSince(from));
    }

    // — 6. LOGIN_REQUIRED with the stored id: renewed, and asked once more —
    {
        const QString stale = QStringLiteral("TESTVISITORstale0001");
        refused = { stale };
        storedAgo(stale, 3600);
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-stale"));
        t.check(!played.url.isEmpty() && orderSince(from) == QLatin1String("player sw player")
                    && lastPlayer().header("x-goog-visitor-id") != stale.toUtf8(),
                QStringLiteral("refused with the stored id: a new id, /player once more, answered"),
                orderSince(from) + QStringLiteral(" ") + played.error);
        t.check(settings.value(idKey) != stale && !settings.value(idKey).isEmpty(),
                QStringLiteral("and the new id replaces the stored one"));

        // Two at once, both refused: one renewal between them.
        storedAgo(stale, 3600);
        launch();
        InnerTube other;
        const int twoFrom = int(standIn.requests.size());
        const auto a = playLater(resolver, QStringLiteral("vid-stale-a"));
        const auto b = playLater(other, QStringLiteral("vid-stale-b"));
        waitUntil([a, b]() { return a->done && b->done; }, 20000);
        t.check(!a->url.isEmpty() && !b->url.isEmpty() && countSince(twoFrom, "/sw.js_data") == 1
                    && countSince(twoFrom, "/player") == 4,
                QStringLiteral("two refused at once share one renewal, and both are answered"), orderSince(twoFrom));

        // — 7. and only once —
        refuseAll = true;
        storedAgo(stale, 3600);
        launch();
        const int onceFrom = int(standIn.requests.size());
        const Played again = playNow(resolver, QStringLiteral("vid-refused"));
        t.check(again.url.isEmpty() && again.error.contains(QLatin1String("LOGIN_REQUIRED"))
                    && orderSince(onceFrom) == QLatin1String("player sw player"),
                QStringLiteral("refused again with the new id: one retry only, then the tier below"),
                orderSince(onceFrom) + QStringLiteral(" ") + again.error);
        const int laterFrom = int(standIn.requests.size());
        const Played later = playNow(resolver, QStringLiteral("vid-refused-later"));
        t.check(later.url.isEmpty() && orderSince(laterFrom) == QLatin1String("player"),
                QStringLiteral("and with an id fetched this launch, LOGIN_REQUIRED is the track's own answer"),
                orderSince(laterFrom));
        refuseAll = false;
        refused.clear();
    }

    // — 8. sw.js_data fails: the home page, as before —
    {
        swFails = true;
        settings.remove(idKey);
        settings.remove(atKey);
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-home"));
        t.check(!played.url.isEmpty() && orderSince(from) == QLatin1String("sw home player")
                    && settings.value(idKey).startsWith(QLatin1String("TESTVISITORhome"))
                    && lastPlayer().header("x-goog-visitor-id") == settings.value(idKey).toUtf8(),
                QStringLiteral("sw.js_data refused: the id is read from the home page"), orderSince(from));
        swFails = false;
    }

    // — 9. no id anywhere (the EU consent page): the stored one is kept —
    {
        const QString stale = QStringLiteral("TESTVISITORkept0001");
        refused = { stale };
        swNoId = true;
        homeNoId = true;
        storedAgo(stale, 3600);
        launch();
        InnerTube resolver;
        const int before = int(captured.size());
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-consent"));
        bool warned = false;
        for (int i = before; i < captured.size(); ++i)
            warned = warned || captured.at(i).contains(QLatin1String("gave no visitor id"));
        t.check(played.url.isEmpty() && orderSince(from) == QLatin1String("player sw home")
                    && settings.value(idKey) == stale && warned,
                QStringLiteral("no id from either: the stored id is kept, a warning logged, the tier below asked"),
                orderSince(from));
        refused.clear();

        // A first launch with no id to be had: /player still goes, without one.
        settings.remove(idKey);
        settings.remove(atKey);
        launch();
        InnerTube first;
        const int noneFrom = int(standIn.requests.size());
        const Played none = playNow(first, QStringLiteral("vid-no-id"));
        t.check(!none.url.isEmpty() && orderSince(noneFrom) == QLatin1String("sw home player")
                    && !lastPlayer().has("x-goog-visitor-id") && visitorOf(lastPlayer()).isEmpty(),
                QStringLiteral("none to be had on a first launch: /player goes without one, as before"),
                orderSince(noneFrom));
        swNoId = false;
        homeNoId = false;
    }

    // — 10. the switch back —
    {
        storedAgo(QStringLiteral("TESTVISITORswitch0001"), 3600);
        settings.insert(modeKey, QStringLiteral("home"));
        launch();
        InnerTube resolver;
        const int from = int(standIn.requests.size());
        const Played played = playNow(resolver, QStringLiteral("vid-mode-home"));
        t.check(!played.url.isEmpty() && orderSince(from) == QLatin1String("home player")
                    && settings.value(idKey).isEmpty(),
                QStringLiteral("youtube.visitor=home: the stored id dropped, the home page fetched, nothing stored"),
                orderSince(from));
        settings.insert(modeKey, QStringLiteral("launch"));
        launch();
        InnerTube other;
        const int launchFrom = int(standIn.requests.size());
        playNow(other, QStringLiteral("vid-mode-launch"));
        t.check(orderSince(launchFrom) == QLatin1String("sw player") && settings.value(idKey).isEmpty(),
                QStringLiteral("youtube.visitor=launch: fetched from sw.js_data, kept for the launch only"),
                orderSince(launchFrom));
        settings.remove(modeKey);
    }

    // — 11. Clear history —
    {
        settings.remove(idKey);
        settings.remove(atKey);
        launch();
        InnerTube resolver;
        playNow(resolver, QStringLiteral("vid-before-clear"));
        const QString before = settings.value(idKey);
        InnerTube::forgetVisitorData();
        InnerTube catalog;
        browseNow(catalog, QStringLiteral("FEtest_cleared"), InnerTube::Auth::Anonymous);
        t.check(settings.value(idKey).isEmpty() && settings.value(atKey).isEmpty()
                    && !standIn.requests.last().header("cookie").contains("VISITOR_INFO1_LIVE"),
                QStringLiteral("forgotten: the stored id and the jar's cookies are gone"));
        const int from = int(standIn.requests.size());
        playNow(resolver, QStringLiteral("vid-after-clear"));
        t.check(orderSince(from) == QLatin1String("sw player") && !settings.value(idKey).isEmpty()
                    && settings.value(idKey) != before,
                QStringLiteral("and the next play starts as a first visit, with a new id"), orderSince(from));
    }

    // — 12. the account's own id, kept apart from the anonymous one —
    {
        InnerTube::AccountHook hook;
        hook.headers = [](InnerTube::Auth auth, const QByteArray &, QByteArray *cookie, QByteArray *) -> quint64 {
            if (auth == InnerTube::Auth::Anonymous)
                return 0;
            *cookie = "SAPISID=TESTSAPISID123";
            return 7;
        };
        InnerTube::setAccountHook(hook);
        const QString sessionId = QStringLiteral("TESTSESSIONvisitor0001");
        const QString anonymous = settings.value(idKey);
        InnerTube tube;
        browseNow(tube, QStringLiteral("FEtest_signed_in"), InnerTube::Auth::IfSignedIn);
        t.check(!standIn.requests.last().has("x-goog-visitor-id") && visitorOf(standIn.requests.last()).isEmpty(),
                QStringLiteral("with no account id supplied, the account's calls name no visitor, as before"));
        InnerTube::setSessionVisitorData(sessionId);
        browseNow(tube, QStringLiteral("FEtest_signed_in"), InnerTube::Auth::IfSignedIn);
        t.check(standIn.requests.last().header("x-goog-visitor-id") == sessionId.toUtf8()
                    && visitorOf(standIn.requests.last()) == sessionId,
                QStringLiteral("with one: the account's call names the account's id"));
        browseNow(tube, QStringLiteral("FEtest_anonymous"), InnerTube::Auth::Anonymous);
        t.check(!standIn.requests.last().has("x-goog-visitor-id"),
                QStringLiteral("an anonymous browse names neither"));
        playNow(tube, QStringLiteral("vid-signed-in"));
        t.check(lastPlayer().header("x-goog-visitor-id") == anonymous.toUtf8() && visitorOf(lastPlayer()) == anonymous,
                QStringLiteral("and /player, anonymous, keeps the anonymous id: the two never meet"));
        InnerTube::setSessionVisitorData(QString());
        InnerTube::setAccountHook({});
    }

    // — 13. the log —
    {
        g_captured = nullptr;
        qInstallMessageHandler(g_previousHandler);
        QStringList found;
        for (const QString &line : std::as_const(captured)) {
            if (line.contains(QLatin1String("TESTVISITOR")) || line.contains(QLatin1String("TESTCOOKIE"))
                || line.contains(QLatin1String("TESTSESSION")) || line.contains(QLatin1String("TESTSAPISID")))
                found << line.left(80);
        }
        t.check(found.isEmpty(), QStringLiteral("none of %1 lines logged holds a visitor id or a cookie value")
                                     .arg(captured.size()), found.join(QStringLiteral(" | ")));
    }

    InnerTube::setVisitorStore({});
    InnerTube::setTestServer(QString());
    settle(50);
    return t.finish();
}

// ---------------------------------------------------------------- the second /player client

namespace {

QJsonObject clientOf(const StandIn::Request &request)
{
    return request.json().value(QStringLiteral("context")).toObject().value(QStringLiteral("client")).toObject();
}

}

int runPlayerClientSelfTest()
{
    Checks t("clients");
    QStringList captured;
    g_captured = &captured;
    g_previousHandler = qInstallMessageHandler(captureMessage);

    StandIn standIn;
    if (!t.check(standIn.listen(), QStringLiteral("a stand-in server on this computer"))) {
        qInstallMessageHandler(g_previousHandler);
        g_captured = nullptr;
        return t.finish();
    }
    InnerTube::setTestServer(standIn.base());
    t.note(QStringLiteral("every request goes to ") + standIn.base() + QStringLiteral(", none to YouTube"));

    // How each client version answers /player: "ok", "login", "unplayable",
    // "cipher" (formats behind signatureCipher only), "drop" (the connection
    // closed unanswered) or "hold" (never answered). An id in `refusedIds`
    // is refused by every version, as a stored id YouTube dropped would be.
    QHash<QString, QString> answerAs;
    QSet<QString> refusedIds;
    int minted = 0;
    QElapsedTimer clock;
    clock.start();
    QList<qint64> arrivals;   // when each request came, parallel to standIn.requests
    standIn.respond = [&](const StandIn::Request &request) {
        arrivals.append(clock.elapsed());
        StandIn::Answer answer;
        if (request.path == "/sw.js_data") {
            answer.body = swJsData(QStringLiteral("TESTVISITORclient%1").arg(++minted, 4, 10, QLatin1Char('0')));
            answer.extra << "Set-Cookie: VISITOR_INFO1_LIVE=TESTCOOKIEclient; Path=/";
            return answer;
        }
        if (!request.path.contains("/player"))
            return answer;
        const QString version = clientOf(request).value(QStringLiteral("clientVersion")).toString();
        const QString how = refusedIds.contains(QString::fromLatin1(request.header("x-goog-visitor-id")))
                                ? QStringLiteral("login") : answerAs.value(version, QStringLiteral("ok"));
        if (how == QLatin1String("ok")) {
            // The URL names the version that gave it, so a check can tell.
            answer.body = R"({"playabilityStatus":{"status":"OK"},"streamingData":{"adaptiveFormats":[)"
                          R"({"itag":251,"url":"http://127.0.0.1/audio-)" + version.toUtf8()
                          + R"(","mimeType":"audio/webm; codecs=\"opus\"","bitrate":130000}]}})";
        } else if (how == QLatin1String("login")) {
            answer.body = R"({"playabilityStatus":{"status":"LOGIN_REQUIRED","reason":"Sign in to confirm you are not a bot"}})";
        } else if (how == QLatin1String("unplayable")) {
            answer.body = R"({"playabilityStatus":{"status":"UNPLAYABLE","reason":"This video is not available"}})";
        } else if (how == QLatin1String("cipher")) {
            answer.body = R"({"playabilityStatus":{"status":"OK"},"streamingData":{"adaptiveFormats":[)"
                          R"({"itag":251,"signatureCipher":"s=TEST&sp=sig&url=http%3A%2F%2F127.0.0.1%2Fciphered",)"
                          R"("mimeType":"audio/webm; codecs=\"opus\"","bitrate":130000}]}})";
        } else if (how == QLatin1String("drop")) {
            answer.drop = true;
        } else {
            answer.hold = true;
        }
        return answer;
    };
    // What was asked since `from`: "sw", or the /player client's version.
    const auto orderSince = [&standIn](int from) {
        QStringList order;
        for (int i = from; i < standIn.requests.size(); ++i) {
            const StandIn::Request &request = standIn.requests.at(i);
            order << (request.path == "/sw.js_data" ? QStringLiteral("sw")
                      : request.path.contains("/player")
                          ? clientOf(request).value(QStringLiteral("clientVersion")).toString()
                          : QStringLiteral("other"));
        }
        return order.join(QLatin1Char(' '));
    };
    const auto loggedSince = [&captured](int from, const QString &text) {
        for (int i = from; i < captured.size(); ++i) {
            if (captured.at(i).contains(text))
                return true;
        }
        return false;
    };

    QHash<QString, QString> settings;
    const auto launch = [&settings]() {
        InnerTube::setVisitorStore({
            [&settings](const QString &key) { return settings.value(key); },
            [&settings](const QString &key, const QString &value) { settings.insert(key, value); } });
    };
    const QString clientKey = QStringLiteral("youtube.player_client");

    // — 1. the first client answers: the second is never asked —
    launch();
    {
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-first-ok"));
        t.check(played.url.endsWith(QLatin1String("audio-1.02")) && orderSince(from) == QLatin1String("sw 1.02"),
                QStringLiteral("VISIONOS 1.02 answers: one /player, as 1.02, and nothing more"), orderSince(from));
    }

    // — 2. refused: the second client, at once, as the same app —
    {
        answerAs.insert(QStringLiteral("1.02"), QStringLiteral("login"));
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const int logFrom = int(captured.size());
        QElapsedTimer took;
        took.start();
        const Played played = playNow(tube, QStringLiteral("vid-first-refused"));
        const qint64 ms = took.elapsed();
        t.check(played.url.endsWith(QLatin1String("audio-0.1")) && orderSince(from) == QLatin1String("1.02 0.1"),
                QStringLiteral("1.02 refused (LOGIN_REQUIRED): asked once as 0.1, which answers"),
                orderSince(from) + QStringLiteral(" ") + played.error);
        const StandIn::Request first = standIn.requests.value(from);
        const StandIn::Request second = standIn.requests.value(from + 1);
        QJsonObject a = clientOf(first);
        QJsonObject b = clientOf(second);
        const bool sameApp = a.value(QStringLiteral("clientName")).toString() == QLatin1String("VISIONOS")
                             && b.value(QStringLiteral("clientVersion")).toString() == QLatin1String("0.1");
        a.remove(QStringLiteral("clientVersion"));
        b.remove(QStringLiteral("clientVersion"));
        t.check(sameApp && a == b && first.header("user-agent") == second.header("user-agent")
                    && !second.header("x-goog-visitor-id").isEmpty()
                    && first.header("x-goog-visitor-id") == second.header("x-goog-visitor-id"),
                QStringLiteral("the second is the same visionOS app, only the version changed: same fields, "
                               "User-Agent and visitor id"));
        const qint64 gap = arrivals.value(from + 1) - arrivals.value(from);
        t.check(gap < 1000, QStringLiteral("and it goes out as soon as the refusal is in (%1 ms later; "
                                           "the whole resolve took %2 ms here)").arg(gap).arg(ms));
        t.check(loggedSince(logFrom, QStringLiteral("gave no plain stream"))
                    && loggedSince(logFrom, QStringLiteral("answered as VISIONOS 0.1")),
                QStringLiteral("the log says why the second was asked, and that it answered"));
    }

    // — 3. an answer with ciphered formats only is no plain stream either —
    {
        answerAs.insert(QStringLiteral("1.02"), QStringLiteral("cipher"));
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-first-cipher"));
        t.check(played.url.endsWith(QLatin1String("audio-0.1")) && orderSince(from) == QLatin1String("1.02 0.1"),
                QStringLiteral("1.02 offers only signatureCipher: 0.1 is asked and answers"), orderSince(from));
    }

    // — 4. both refuse: one error naming both, and the time it took —
    {
        answerAs.insert(QStringLiteral("1.02"), QStringLiteral("unplayable"));
        answerAs.insert(QStringLiteral("0.1"), QStringLiteral("unplayable"));
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const int logFrom = int(captured.size());
        const Played played = playNow(tube, QStringLiteral("vid-both-refuse"));
        t.check(played.url.isEmpty() && orderSince(from) == QLatin1String("1.02 0.1")
                    && played.error.contains(QLatin1String("VISIONOS 1.02: UNPLAYABLE: This video is not available"))
                    && played.error.contains(QLatin1String("VISIONOS 0.1: UNPLAYABLE")),
                QStringLiteral("both refuse: two /player calls, then the tier below, told why by each"),
                orderSince(from) + QStringLiteral(" / ") + played.error);
        t.check(loggedSince(logFrom, QStringLiteral("vid-both-refuse not resolved in")),
                QStringLiteral("and the log has why InnerTube failed and how long it took"));
    }

    // — 5. no answer at all: the second client is not asked —
    {
        answerAs.insert(QStringLiteral("1.02"), QStringLiteral("drop"));
        answerAs.remove(QStringLiteral("0.1"));
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-first-dropped"));
        t.check(played.url.isEmpty() && !orderSince(from).contains(QLatin1String("0.1"))
                    && played.error.startsWith(QLatin1String("VISIONOS 1.02: ")),
                QStringLiteral("1.02 unanswered (the connection closed): its own retry only, never 0.1"),
                orderSince(from) + QStringLiteral(" / ") + played.error);
    }

    // — 6. a stored id refused: renewed and asked again first, then 0.1 —
    {
        const QString stale = QStringLiteral("TESTVISITORclientstale");
        settings.insert(QStringLiteral("youtube.visitor_data"), stale);
        settings.insert(QStringLiteral("youtube.visitor_data_at"),
                        QDateTime::currentDateTimeUtc().addSecs(-3600).toString(Qt::ISODate));
        refusedIds = { stale };
        answerAs.insert(QStringLiteral("1.02"), QStringLiteral("login"));
        launch();
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-stale-then-second"));
        const StandIn::Request last = standIn.requests.last();
        t.check(played.url.endsWith(QLatin1String("audio-0.1")) && orderSince(from) == QLatin1String("1.02 sw 1.02 0.1")
                    && !last.header("x-goog-visitor-id").isEmpty() && last.header("x-goog-visitor-id") != stale.toUtf8(),
                QStringLiteral("refused with the stored id: a new id, 1.02 once more, then 0.1 with the new id"),
                orderSince(from));
        refusedIds.clear();
    }

    // — 7. the second client gets no retry and a shorter wait —
    {
        answerAs.insert(QStringLiteral("0.1"), QStringLiteral("hold"));
        InnerTube tube;
        const int from = int(standIn.requests.size());
        QElapsedTimer took;
        took.start();
        const Played played = playNow(tube, QStringLiteral("vid-second-silent"));
        const qint64 ms = took.elapsed();
        t.check(played.url.isEmpty() && orderSince(from) == QLatin1String("1.02 0.1") && ms >= 2500 && ms < 6000
                    && played.error.contains(QLatin1String("VISIONOS 0.1: ")),
                QStringLiteral("0.1 never answers: given up after %1 ms, not retried").arg(ms),
                orderSince(from) + QStringLiteral(" / ") + played.error);
        answerAs.remove(QStringLiteral("0.1"));
    }

    // — 8. the switch: the first client alone, as before —
    {
        settings.insert(clientKey, QStringLiteral("first"));
        launch();
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-switch-first"));
        t.check(played.url.isEmpty() && orderSince(from).endsWith(QLatin1String("1.02"))
                    && !orderSince(from).contains(QLatin1String("0.1")),
                QStringLiteral("youtube.player_client=first: 1.02 refused, and 0.1 never asked"), orderSince(from));
    }

    // — 9. and the second client alone, for the canary and the resolve test —
    {
        answerAs.remove(QStringLiteral("1.02"));
        settings.insert(clientKey, QStringLiteral("second"));
        launch();
        InnerTube tube;
        const int from = int(standIn.requests.size());
        const Played played = playNow(tube, QStringLiteral("vid-switch-second"));
        t.check(played.url.endsWith(QLatin1String("audio-0.1")) && orderSince(from).endsWith(QLatin1String("0.1"))
                    && !orderSince(from).contains(QLatin1String("1.02")),
                QStringLiteral("youtube.player_client=second: 0.1 alone, though 1.02 would have answered"),
                orderSince(from));
        InnerTube::setPlayerClients(InnerTube::PlayerClients::Both);
        const int bothFrom = int(standIn.requests.size());
        playNow(tube, QStringLiteral("vid-override"));
        t.check(orderSince(bothFrom) == QLatin1String("1.02"),
                QStringLiteral("setPlayerClients overrides the setting until the next launch"), orderSince(bothFrom));
        settings.remove(clientKey);
    }

    // — 10. the log —
    {
        g_captured = nullptr;
        qInstallMessageHandler(g_previousHandler);
        QStringList found;
        for (const QString &line : std::as_const(captured)) {
            if (line.contains(QLatin1String("TESTVISITOR")) || line.contains(QLatin1String("TESTCOOKIE")))
                found << line.left(80);
        }
        t.check(found.isEmpty(), QStringLiteral("none of %1 lines logged holds a visitor id or a cookie value")
                                     .arg(captured.size()), found.join(QStringLiteral(" | ")));
    }

    InnerTube::setVisitorStore({});
    InnerTube::setTestServer(QString());
    settle(50);
    return t.finish();
}
